name: Testing
on:
  push:
  pull_request:
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Running time benchmark
        run: yarn bench
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 17
          - 16
          - 14
          - 12
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Run unit tests
        run: yarn test
        env:
          FORCE_COLOR: 2
